theme: jekyll-theme-minimal
show_downloads: false
title: Post Pump - Land Use and Zoning for an Electric Vehicle World
logo: docs/assets/nabgas.png
description: Post Pump is an organization providing resources and research to pursuade City, County, and State Land Use and Zoning code updates to protect taxpayers from abandoned fuel stations in an electric vehcile future
whitelist:
  - jekyll-redirect-from
plugins:
  - jekyll-redirect-from
